### ISSUE TITLE
AttributeError in SysLogHandler

### ISSUE THREAD

**Issue by wrpscott** [xolox/python-rotate-backups#9] opened 2018-02-01 21:40 UTC
Hello and thank you for a useful package.
invoking 'python -v' gives me 'Python 3.5.4'.
invoking 'rotate-backups -h' gives me the help screen, but then:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1888, in shutdown
    h.close()
  File "/usr/local/lib/python3.5/logging/handlers.py", line 882, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'

(I got this with python 3.6, which according to your website is not supported, as well).
The package was installed via pip into a python:3.5-jessie docker image.

**Comment by calebdelnay** [comment] 2018-11-09 15:39
This issue happens if `rotate-backups` is used on a system that doesn't have a syslog socket available (like at `/dev/log`).

Docker containers don't have a syslog socket and logs are typically collected from the container's stdout.

@xolox Do you have a suggestion on how to disable syslog logging for python-rotate-backups?

**Comment by MaxWinterstein** [comment] 2019-02-27 11:37
Indeed, i can confirm this problem when trying to use (this awesome tool!) inside some docker container. 

Using python 3.7 instead python 3.6 solved the problem for me. Both of them are build equally onto a debian-slim stretch image.

**Comment by MaxWinterstein** [comment] 2019-02-27 11:44
Note: If you rely on using your not working version of python you can change this inside your packe url: https://github.com/xolox/python-rotate-backups/blob/611c72b2806952bf2bb84c38a4b5f856ea334707/rotate_backups/cli.py#L207

Edit the `cli.py` file (location when using venvs: `vim /venv/lib/python3.6/site-packages/rotate_backups/cli.py` and do this:
```diff
- coloredlogs.install(syslog=True)
+ coloredlogs.install(syslog=False)
```

Or you could simply inject something like 
```bash
sed -i 's/syslog=True/syslog=False/' /venv/lib/python3.7/site-packages/rotate_backups/cli.py 
```
into your Dockerfile - if you use one.

**Comment by breuerfelix** [comment] 2019-07-23 14:32
would be cool if we could disable this via command line.

Are there any plans on adding this ? would you merge it if I write this little fix ?

**Comment by danjl1100** [comment] 2020-04-21 02:26
Found the docker file fix above from Google, then realized passing `--syslog=0`  does the same thing!
Probably can close this as "Fixed in ed1c56c4fefb575922082df7c676a6536f864619".

**Comment by xolox** [comment] 2020-04-25 21:16
Thanks for the feedback everyone, as @danjl1100 suggested the new(-ish) command line option `rotate-backups --syslog=false` can be used to avoid this issue. For now I'll close this but if anyone has feedback to add, please feel free to share.

**Closed by xolox** 2020-04-25 21:16 UTC

**Comment by xolox** [comment] 2020-12-10 13:33
A bit more context about this issue that I've recently come to understand a bit better:

- This happens when the Python interpreter shuts down and `/dev/log` was given to `SysLogHandler` but doesn't exist, see also [#38780](https://bugs.python.org/issue38780). This seems like a bug in the Python interpreter, although possibly a bit of an undefined edge case.
- One example of this happening is on MacOS because there `/dev/log` doesn't exist, period. As of coloredlogs [release 15.0](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-15-0-2020-12-10) system logging is no longer enabled on MacOS because of this.
- Clearly this can also affect Linux, I assume this concerns (Docker) containers that may not expose `/dev/log`? (I'm just thinking out loud here, this is not first hand experience)
